version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # You will create this later
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # You will create this later
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # This tells Docker Compose to load variables from a .env file
    env_file:
      - ./backend/.env